import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";

const inter = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Book App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://image.pngaaa.com/529/1773529-middle.png"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
